"""Impossible travel between successful authentications.

MITRE ATT&CK: T1078 (Valid Accounts), tactic Initial Access.

All geolocation in this project is synthetic and generated by the telemetry
service. Nothing is looked up externally.
"""

from __future__ import annotations

from pydantic import Field
from sqlalchemy import select

from app.core.enums import EventOutcome, EventType, Severity
from app.detection.base import (
    AlertCandidate,
    DetectionContext,
    DetectionRule,
    RuleConfig,
    haversine_km,
    time_bucket,
)
from app.detection.registry import register
from app.models.event import SecurityEvent


class ImpossibleTravelConfig(RuleConfig):
    # Roughly commercial-aircraft cruising speed. Anything faster implies the
    # same credential is in use in two places at once.
    max_speed_kmh: float = Field(default=900.0, gt=0, le=10000)
    window_minutes: int = Field(default=720, ge=5, le=10080)
    # Below this distance, geolocation error dominates and the speed figure is
    # meaningless. Prevents alerting on two offices in the same city.
    min_distance_km: float = Field(default=500.0, ge=0, le=20000)


@register
class ImpossibleTravelRule(DetectionRule):
    key = "impossible_travel"
    name = "Impossible Travel"
    description = (
        "The same account authenticates successfully from two locations that "
        "are too far apart to be reached in the elapsed time."
    )
    default_severity = Severity.HIGH
    default_confidence = 75
    mitre_tactic = "Initial Access"
    mitre_technique_id = "T1078"
    mitre_technique_name = "Valid Accounts"
    config_model = ImpossibleTravelConfig

    def evaluate(self, ctx: DetectionContext) -> list[AlertCandidate]:
        cfg = ImpossibleTravelConfig(**ctx.config)

        logins = [
            e
            for e in ctx.events
            if e.event_type == EventType.AUTHENTICATION.value
            and e.outcome == EventOutcome.SUCCESS.value
            and e.username
            and e.latitude is not None
            and e.longitude is not None
        ]
        if not logins:
            return []

        candidates: list[AlertCandidate] = []
        seen_keys: set[str] = set()

        for login in logins:
            previous = (
                ctx.db.execute(
                    select(SecurityEvent)
                    .where(
                        SecurityEvent.username == login.username,
                        SecurityEvent.event_type == EventType.AUTHENTICATION.value,
                        SecurityEvent.outcome == EventOutcome.SUCCESS.value,
                        SecurityEvent.timestamp >= ctx.window_start(cfg.window_minutes),
                        SecurityEvent.timestamp < login.timestamp,
                        SecurityEvent.latitude.is_not(None),
                    )
                    .order_by(SecurityEvent.timestamp.desc())
                    .limit(1)
                )
                .scalars()
                .first()
            )
            if previous is None:
                continue

            distance = haversine_km(
                previous.latitude, previous.longitude, login.latitude, login.longitude
            )
            if distance < cfg.min_distance_km:
                continue

            hours = (login.timestamp - previous.timestamp).total_seconds() / 3600.0
            # Two locations at the same instant means infinite required speed.
            required_speed = float("inf") if hours <= 0 else distance / hours
            if required_speed <= cfg.max_speed_kmh:
                continue

            key = f"{self.key}|{login.username}|{time_bucket(login.timestamp, 60)}"
            if key in seen_keys:
                continue
            seen_keys.add(key)

            speed_text = (
                "instantaneously" if hours <= 0 else f"{required_speed:,.0f} km/h"
            )
            candidates.append(
                AlertCandidate(
                    dedup_key=key,
                    title=f"Impossible travel for '{login.username}'",
                    description=(
                        f"Account '{login.username}' authenticated from "
                        f"{previous.city or previous.country_code or 'an unknown location'} "
                        f"and then from {login.city or login.country_code or 'an unknown location'} "
                        f"{hours:.1f} hours later. Covering {distance:,.0f} km in that time "
                        f"requires travelling at {speed_text}, above the {cfg.max_speed_kmh:,.0f} km/h "
                        f"threshold. This usually means the credential is in use by two parties."
                    ),
                    severity=Severity.HIGH,
                    confidence=80,
                    event_ids=[previous.id, login.id],
                    first_seen=previous.timestamp,
                    last_seen=login.timestamp,
                    src_ip=login.src_ip,
                    username=login.username,
                    hostname=login.hostname,
                    evidence={
                        "distance_km": round(distance, 1),
                        "elapsed_hours": round(hours, 2),
                        "required_speed_kmh": (
                            None if hours <= 0 else round(required_speed, 1)
                        ),
                        "threshold_kmh": cfg.max_speed_kmh,
                        "from_location": previous.city or previous.country_code,
                        "to_location": login.city or login.country_code,
                        "from_ip": previous.src_ip,
                        "to_ip": login.src_ip,
                    },
                )
            )
        return candidates
