"""initial schema

Revision ID: a2e31d8206e3
Revises: 
Create Date: 2026-09-03 08:37:46.766370
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# JSONB's astext_type is rendered bare by autogenerate; import it so the
# module is valid on its own.
from sqlalchemy import Text

revision: str = 'a2e31d8206e3'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=64), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=16), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_rules')),
    sa.UniqueConstraint('rule_key', name=op.f('uq_detection_rules_rule_key'))
    )
    op.create_index(op.f('ix_detection_rules_created_at'), 'detection_rules', ['created_at'], unique=False)
    op.create_index('ix_detection_rules_enabled', 'detection_rules', ['enabled'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('bytes_received', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('process_name', sa.String(length=128), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('url_path', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('dns_query', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events')),
    sa.UniqueConstraint('event_uid', name=op.f('uq_security_events_event_uid'))
    )
    op.create_index('ix_events_analyzed_timestamp', 'security_events', ['analyzed', 'timestamp'], unique=False)
    op.create_index('ix_events_dst_ip_timestamp', 'security_events', ['dst_ip', 'timestamp'], unique=False)
    op.create_index('ix_events_severity_timestamp', 'security_events', ['severity', 'timestamp'], unique=False)
    op.create_index('ix_events_src_ip_timestamp', 'security_events', ['src_ip', 'timestamp'], unique=False)
    op.create_index('ix_events_type_timestamp', 'security_events', ['event_type', 'timestamp'], unique=False)
    op.create_index('ix_events_username_timestamp', 'security_events', ['username', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_actor_timestamp', 'audit_logs', ['actor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_uid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_incidents_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_incidents_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('incident_uid', name=op.f('uq_incidents_incident_uid'))
    )
    op.create_index('ix_incidents_assigned_status', 'incidents', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_severity_created', 'incidents', ['severity', 'created_at'], unique=False)
    op.create_index('ix_incidents_status_created', 'incidents', ['status', 'created_at'], unique=False)
    op.create_table('ioc_watchlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=True),
    sa.Column('added_by_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_ioc_watchlist_added_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ioc_watchlist')),
    sa.UniqueConstraint('ioc_type', 'value', name='uq_ioc_type_value')
    )
    op.create_index('ix_ioc_active_type', 'ioc_watchlist', ['active', 'ioc_type'], unique=False)
    op.create_index(op.f('ix_ioc_watchlist_created_at'), 'ioc_watchlist', ['created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_uid', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=16), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=128), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=64), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_alerts_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], name=op.f('fk_alerts_rule_id_detection_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('alert_uid', name=op.f('uq_alerts_alert_uid')),
    sa.UniqueConstraint('dedup_key', name='uq_alerts_dedup_key')
    )
    op.create_index('ix_alerts_assigned_status', 'alerts', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_incident', 'alerts', ['incident_id'], unique=False)
    op.create_index('ix_alerts_rule_created', 'alerts', ['rule_key', 'created_at'], unique=False)
    op.create_index('ix_alerts_severity_created', 'alerts', ['severity', 'created_at'], unique=False)
    op.create_index('ix_alerts_src_ip', 'alerts', ['src_ip'], unique=False)
    op.create_index('ix_alerts_status_created', 'alerts', ['status', 'created_at'], unique=False)
    op.create_table('incident_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_incident_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_notes_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_notes'))
    )
    op.create_index(op.f('ix_incident_notes_created_at'), 'incident_notes', ['created_at'], unique=False)
    op.create_index('ix_incident_notes_incident_created', 'incident_notes', ['incident_id', 'created_at'], unique=False)
    op.create_table('incident_timeline_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_timeline_entries_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_timeline_entries'))
    )
    op.create_index(op.f('ix_incident_timeline_entries_created_at'), 'incident_timeline_entries', ['created_at'], unique=False)
    op.create_index('ix_timeline_incident_occurred', 'incident_timeline_entries', ['incident_id', 'occurred_at'], unique=False)
    op.create_table('alert_events',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_events_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], name=op.f('fk_alert_events_event_id_security_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'event_id', name=op.f('pk_alert_events'))
    )
    op.create_index('ix_alert_events_event_id', 'alert_events', ['event_id'], unique=False)
    op.create_table('alert_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_notes_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_alert_notes_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_notes'))
    )
    op.create_index('ix_alert_notes_alert_created', 'alert_notes', ['alert_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alert_notes_created_at'), 'alert_notes', ['created_at'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.Uuid(), nullable=True),
    sa.Column('performed_by_email', sa.String(length=320), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_response_actions_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_response_actions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_response_actions_performed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_actions'))
    )
    op.create_index(op.f('ix_response_actions_created_at'), 'response_actions', ['created_at'], unique=False)
    op.create_index('ix_response_actions_incident', 'response_actions', ['incident_id', 'created_at'], unique=False)
    op.create_index('ix_response_actions_type', 'response_actions', ['action_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_actions_type', table_name='response_actions')
    op.drop_index('ix_response_actions_incident', table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_created_at'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_alert_notes_created_at'), table_name='alert_notes')
    op.drop_index('ix_alert_notes_alert_created', table_name='alert_notes')
    op.drop_table('alert_notes')
    op.drop_index('ix_alert_events_event_id', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_timeline_incident_occurred', table_name='incident_timeline_entries')
    op.drop_index(op.f('ix_incident_timeline_entries_created_at'), table_name='incident_timeline_entries')
    op.drop_table('incident_timeline_entries')
    op.drop_index('ix_incident_notes_incident_created', table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_created_at'), table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_index('ix_alerts_status_created', table_name='alerts')
    op.drop_index('ix_alerts_src_ip', table_name='alerts')
    op.drop_index('ix_alerts_severity_created', table_name='alerts')
    op.drop_index('ix_alerts_rule_created', table_name='alerts')
    op.drop_index('ix_alerts_incident', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index('ix_alerts_assigned_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ioc_watchlist_created_at'), table_name='ioc_watchlist')
    op.drop_index('ix_ioc_active_type', table_name='ioc_watchlist')
    op.drop_table('ioc_watchlist')
    op.drop_index('ix_incidents_status_created', table_name='incidents')
    op.drop_index('ix_incidents_severity_created', table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('ix_incidents_assigned_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_action_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index('ix_events_username_timestamp', table_name='security_events')
    op.drop_index('ix_events_type_timestamp', table_name='security_events')
    op.drop_index('ix_events_src_ip_timestamp', table_name='security_events')
    op.drop_index('ix_events_severity_timestamp', table_name='security_events')
    op.drop_index('ix_events_dst_ip_timestamp', table_name='security_events')
    op.drop_index('ix_events_analyzed_timestamp', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_detection_rules_enabled', table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_created_at'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
